apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: demowebappinstance
  description: demowebappinstance
spec:
  owner: group:default/prayankag
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demowebappinstance
  description: demowebappinstance
  annotations:
     backstage.io/techdocs-ref: dir:./docs
     github.com/project-slug: prayankag/demowebinstance
     github-actions: enabled
     github.com/workflows: |
      [
        {
          "workflow": "instance.yaml",
          "label": "Start",
          "tooltip": "click here and start the workflow process"
        }
      ]
spec:
  type: service
  owner: group:default/prayankag
  lifecycle: experimental
  system: demowebappinstance
  providesApis:
    - demowebappinstance
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demowebappinstance
  description: demowebappinstance
spec:
  type: internal
  lifecycle: experimental
  owner: group:default/prayankag
  system: demowebappinstance
  definition: "demowebappinstance"
