name: Terraform and Dotnet Deployment Workflow

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:
    inputs:
      resourcetype:
        description: 'resourcetype to deploy (e.g., VM , Webapp)'
        required: true
        type: string
      environment:
        description: 'Environment to deploy (e.g., dev, prod)'
        required: true
        type: string
      appname:
        description: 'The Azure Web App name for deployment'
        required: true
        type: string
      infraprovision:
        description: 'Only perform an infrastructure provision'
        required: true
        type: boolean
      webappdeployment:
        description: 'Only perform a webapp deployment'
        required: true
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  # Display input values for debugging
  display-input-values:
    runs-on: ubuntu-latest
    steps:
      - name: Display Input Values
        run: |
          echo "Resource Type: ${{ '${{ github.event.inputs.resourcetype }}' }} "
          echo "Environment: ${{ '${{ github.event.inputs.environment }}' }}"
          echo "App Name: ${{ '${{ github.event.inputs.appname }}' }}"
          echo "Infra Provision: ${{ '${{ github.event.inputs.infraprovision }}' }}"
          echo "Web App Deployment: ${{ '${{ github.event.inputs.webappdeployment }}' }}"
  check-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Check and Trigger Terraform Deployment
        if: ${{ '${{ github.event.inputs.infraprovision }}' }}
        env:
          API_TOKEN: "${{ '${{ secrets.API_TOKEN }}' }}"
        run: |
          echo "Triggering Terraform Deployment Workflow..."
          gh workflow run terraform_deploy.yaml \
            -f resourcetype="${{ '${{ github.event.inputs.resourcetype }}' }}" \
            -f environment="${{ '${{ github.event.inputs.environment }}' }}" \
            -f appname="${{ '${{ github.event.inputs.appname }}' }}"

      - name: Check and Trigger Dotnet Deployment
        if: ${{ '${{ github.event.inputs.webappdeployment }}' }}
        env:
          API_TOKEN: "${{ '${{ secrets.API_TOKEN }}' }}"
        run: |
          echo "Triggering Dotnet Deployment Workflow..."
          gh workflow run dotnet_deploy.yaml \
            -f appname="${{ '${{ github.event.inputs.appname }}' }}" \
            -f environment="${{ '${{ github.event.inputs.environment }}' }}"
